language: objective-c
osx_image: xcode7.1

before_script:
  - brew install couchdb
  - couchdb &

script:
  - ./setup.rb
  - set -o pipefail && xcodebuild -workspace ObjectiveCloudant.xcworkspace/ -scheme ObjectiveCloudantTests -destination 'platform=iOS Simulator,OS=latest,name=iPhone 4S' build test |  xcpretty
  - pod lib lint
